### ISSUE TITLE
very slow on long (base64 encoded) strings

### ISSUE THREAD

**Issue by smason** [tsyrogit/zxcvbn-c#28]
this algorithm gets very slow on long strings hence the original upstream version recommends [truncating long inputs to 100 characters](https://github.com/dropbox/zxcvbn/#runtime-latency), for example see https://github.com/dropbox/zxcvbn/issues/69 for downstream projects running into issues

the specific issue I have is zxcvbn being used in [keepassxc](https://github.com/keepassxreboot/keepassxc), and recently running into [an issue ](https://github.com/keepassxreboot/keepassxc/issues/7712) that causes the UI to become unresponsive for a minute or so.  this was due to another program instructing keepass to store multiple [JSON Web Tokens](https://jwt.io/) and keepass using zxcvbn to calculate password quality for each one

these secrets (not really "passwords") are large JWTs; which are basically base64 encoded strings which take a long time for this package to check.  for example, you can create a string via the following Python code:

```python
base64.b64encode(random.randbytes(num_bytes))
```

running `ZxcvbnMatch` on this takes multiple seconds when run with `num_bytes > 2000`, with the reported entropy being some suitably large number

**Comment by smason** [comment]
0745d23a835be0e61fad61ec44fafff8376055b0 looks like you're putting more effort into giving an estimate than I'd bother with. any secret with more than a few hundred bits of entry is beyond any feasible brute forcing, but I guess it's nice to give some sort of number back

thanks!

**Comment by droidmonkey** [comment]
Concur, can you shift your PR to just incorporate this latest version of zxcvbn. Although we do "prefer" the system's version of the library... which will backfire on Linux distros (the prime target for the fix). So more thought needs to be put into place on whether we decide to fully embed the code or allow the user to choose system or internal. I prefer the former.

**Comment by Tostino** [comment]
Glad to see this was fixed already in your implementation. I was issuing warnings to other implementations due to some reports of crafted password attacks from users of my library.

There is even an exploit script written to target libraries like this: https://github.com/twosixlabs/acsploit/blob/fd5602adf9f312482b8010abf6b4691f08929bc4/acsploit/exploits/passwords/zxcvbn.py

The length limitation seems to do alright in stopping things from getting out of hand, even with specially crafted passwords you can still only get on the order of hundreds of milliseconds to make a guess (with my implementation at least).
